name: save_me
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:

  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.4

  json_annotation: ^4.8.1
  http: any
  shared_preferences: ^2.2.2
  lottie: ^2.6.0
  status_change: ^2.0.0

  counter: ^0.2.2
  flutter_bloc: ^7.1.0
  intl_phone_number_input: ^0.7.3+1
  flutter_svg: ^2.0.9

  image_picker: ^1.0.4
  image_cropper: 4.0.1

  hexcolor: ^3.0.1
  bouncing_button: ^0.0.1+2
  flutter_speed_dial: ^7.0.0

  google_places_flutter: ^2.0.6
  google_maps_webservice: ^0.0.19
  google_maps_place_picker: ^2.0.0

  google_maps_flutter: ^2.5.0
  flutter_typeahead: ^4.0.2

  get: ^4.6.6
  connectivity_plus: ^5.0.2

  flutter_screenutil: ^5.9.0
  provider: ^5.0.0

  maps_places_autocomplete: ^0.0.2
  flutter_phoenix: ^1.1.1
  intl: ^0.18.1
  flutter_bounce: ^1.1.0
  bounceable_effect: ^0.0.1
  qr_flutter: ^4.1.0
  pretty_qr_code: ^3.0.0
  share_plus: ^7.2.1
  geocoding: ^2.1.1
  ndialog: ^4.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/icon_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff" # adaptive icon background color, default is "#ffffff"
  remove_alpha_ios: true # remove alpha from ios, default is true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/
    - assets/anim/
    - assets/fonts/
    - assets/images/black_logo.svg
    - assets/images/black_icon.svg


  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
    - family: abel
      fonts:
        - asset: assets/fonts/abel-regular.ttf
    - family: TitilliumWeb-Bold
      fonts:
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
    - family: TitilliumWeb-Regular
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
    - family: TitilliumWeb-SemiBold
      fonts:
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
